# Generated by Django 4.1 on 2022-09-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechaCreacion', models.DateField()),
                ('distribuidor', models.CharField(max_length=60)),
                ('desarrolladora', models.CharField(max_length=60)),
                ('plataforma', models.CharField(max_length=60)),
                ('puntaje', models.IntegerField()),
                ('genero', models.CharField(max_length=60)),
                ('subGenero', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.CharField(max_length=120)),
                ('fechaError', models.DateField()),
                ('juego', models.CharField(max_length=60)),
                ('plataforma', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('IdJugador', models.CharField(max_length=60)),
                ('celular', models.IntegerField()),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('juego', models.CharField(max_length=60)),
            ],
        ),
    ]
